# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import movie.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.CharField(blank=True, default='Year', max_length=120, null=True)),
                ('studio', models.CharField(blank=True, max_length=120, null=True, validators=[movie.validators.Validate_studio])),
                ('genre', models.CharField(choices=[('seleccionar', 'Seleccionar'), ('accion', 'Accion'), ('comedia', 'Comedia'), ('terror', 'Terror')], default='seleccionar', max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
