# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('seleccionar', 'Seleccionar'), ('Accion', 'Accion'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Romance', 'Romance'), ('Infantil', 'Infantil'), ('Anime', 'Anime'), ('Dorama', 'Dorama'), ('Drama', 'Drama')], default='seleccionar', max_length=120),
        ),
    ]
